[package]
name = "shared-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.2", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.11", features = ["v4"] }