[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.2", features = ["derive"] }
bincode = "1.3"
uuid = { version = "1.11", features = ["v4"] }
leptos = { version = "0.7.7", optional = true} 

[features]
frontend = ["dep:leptos"]